### ISSUE TITLE
Geiser does not work with Guile 2.1.x

### ISSUE THREAD

**Issue by davexunit** [jaor/geiser#112]
As you may already know, Guile's 2.2 pre-release, version 2.1.1, was released a little while ago.  It features a new VM and compiler, which breaks the current Geiser integration.  Below is an excerpt from the #guile IRC channel that explains the problem and the potential solution:

```
<rekado> hmm, can't use 2.1.1. When I send expressions to the REPL via Geiser I get "ERROR: no such language objcode"
<rekado> if I paste the expression directly I get a compilation error: ERROR: In procedure load-thunk-from-memory: not an ELF file
<rekado> probably need to recompile all my modules.
<wingo>	yeah geiser doesn't work with master
<wingo>	unhappily
<rekado> back to regular expressions then...
<amz3>	wingo: do you know what the fix for geiser should be?
<wingo>	amz3: mostly. it needs to compile to 'bytecode instead of 'objcode and then use load-thunk-from-memory instead of objcode->program or whatever it's doing now
<wingo>	there might be more things, i don't know.
<wingo>	but that's the big one. more generally it should know whether it's working with guile 2.0 or 2.2 and be able to do different things.
```

**Comment by jaor** [comment]
@davexunit do you know if there's a cond-expand feature differentiating 2 from 2.2?

**Comment by davexunit** [comment]
Yes, there is.  From the 2.1.1 release notes:

>** New `cond-expand' feature: `guile-2.2'
>
>Use this feature if you need to check for Guile 2.2 from Scheme code.

**Comment by jaor** [comment]
@davexunit thanks a lot.  i've just pushed a patch that (tries to) fix this issue via cond-expand.  please let me know how it works for you!
