### PR TITLE
[FIX #112] Guile Evaluation tests upon version, using bytecode if > 2…

### LINKED ISSUE #112: Geiser does not work with Guile 2.1.x
As you may already know, Guile's 2.2 pre-release, version 2.1.1, was released a little while ago.  It features a new VM and compiler, which breaks the current Geiser integration.  Below is an excerpt from the #guile IRC channel that explains the problem and the potential solution:

```
<rekado> hmm, can't use 2.1.1. When I send expressions to the REPL via Geiser I get "ERROR: no such language objcode"
<rekado> if I paste the expression directly I get a compilation error: ERROR: In procedure load-thunk-from-memory: not an ELF file
<rekado> probably need to recompile all my modules.
<wingo>	yeah geiser doesn't work with master
<wingo>	unhappily
<rekado> back to regular expressions then...
<amz3>	wingo: do you know what the fix for geiser should be?
<wingo>	amz3: mostly. it needs to compile to 'bytecode instead of 'objcode and then use load-thunk-from-memory instead of objcode->program or whatever it's doing now
<wingo>	there might be more things, i don't know.
<wingo>	but that's the big one. more generally it should know whether it's working with guile 2.0 or 2.2 and be able to do different things.
```

### PR DESCRIPTION
**Pull request by turbopape**
….0.X (2.1.X etc...)
This makes evaluation works for Guile 2.1.X, and so addresses #112

### CODE REVIEW

File: scheme/guile/geiser/evaluation.scm [hunk 1]
```diff
@@ -70,14 +71,24 @@
          (ev (lambda ()
                (call-with-values
                    (lambda ()
-                     (let* ((o (compile form
-                                        #:to 'objcode
+                     (let* ((min-ver (string->number
+				      (cadr
+				       (string-split
+					(version) #\.))))
```
Comment (jaor) [inline scheme/guile/geiser/evaluation.scm]: this is just `(minor-version)`

File: scheme/guile/geiser/evaluation.scm [hunk 2]
```diff
@@ -70,14 +71,24 @@
...
+			    (compilation-target  (cond
+						  ((> min-ver 0) 'bytecode)
+						  (else  'objcode)))
+			    (compilation-fn (cond
+					     ((> min-ver 0)  load-thunk-from-memory)
```
Comment (jaor) [inline scheme/guile/geiser/evaluation.scm]: instead of repeating the check, we could just have something like `(bytecode? (string=? "0" (minor-version)))` and use that boolean flag.

File: scheme/guile/geiser/evaluation.scm [hunk 3]
```diff
@@ -70,14 +71,24 @@
...
                                         #:env module
                                         #:opts opts))
-                            (thunk (make-program o)))
-                       (start-stack 'geiser-evaluation-stack
-                                    (eval `(,thunk) module))))
-                 (lambda vs vs)))))
+                            (thunk (compilation-fn o)))
+		       (start-stack 'geiser-evaluation-stack
+				    (eval `(,thunk) module))))
+		 (lambda vs vs)))))
```
Comment (jaor) [inline scheme/guile/geiser/evaluation.scm]: github is showing changes in whitespace... please make sure you didn't introduce any tabs (maybe you didn't)

**Comment by turbopape** [comment]
I addressed you remarks.
I fixed the tabs, used minor version.
But the correct flag is bytecode? is not= "0", as at 2.0.X we still use objcode.
I also rebased.

**Comment by jaor** [comment]
hmmm... this change breaks guile 2.0, because `(system vm loader)` is not available (also there's still tabs, but that's minor).  some kind of compile-time cond is needed, perhaps cond-expand, if a feature for 2.1 is provided (that would also substitute the check for minor-version)... investigating...

**Comment by jaor** [comment]
@turbopape i've pushed an alternative patch using cond-expand, so i'm closing this PR.  thanks nevertheless for your help!!

**Comment by turbopape** [comment]
No problem,as I  am new to guile, I  found this little exchange very
interesting, I learnt a lot, thank you !
